### ISSUE TITLE
Error while running main.py

### ISSUE THREAD

**Issue by Kashish121** [ghostbbbmt/Traffic-Sign-Classification#10]
```
>python main.py
Loading data from data.png ...
./dataset/0/(1).png
./dataset/0/(10).png
.
.
.
.
./dataset/12/(163).png
./dataset/12/(164).png
(1469, 32, 32)
Shuffle data ...
Deskew images ...
Defining HoG parameters ...
Calculating HoG descriptor for every image ...
Spliting data into training (90%) and test set (10%)...
Training SVM model ...
Saving SVM model ...
Frame:0
Traceback (most recent call last):
  File "main.py", line 384, in <module>
    main(args)
  File "main.py", line 272, in main
    coordinate, image, sign_type, text = localization(frame, args.min_size_components, args.similitary_contour_with_circle, model, count, current_sign)
  File "main.py", line 171, in localization
    sign, coordinate = findLargestSign(original_image, contours, similitary_contour_with_circle, 15)
  File "main.py", line 122, in findLargestSign
    M = cv2.moments(c)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wwma2wne\opencv\modules\imgproc\src\moments.cpp:602: error: (-210:Unsupported format or combination of formats)  in function 'cv::moments'
```
Could you help me out with this problem?

**Comment by Anupreetadas** [comment]
> ```
> >python main.py
> Loading data from data.png ...
> ./dataset/0/(1).png
> ./dataset/0/(10).png
> .
> .
> .
> .
> ./dataset/12/(163).png
> ./dataset/12/(164).png
> (1469, 32, 32)
> Shuffle data ...
> Deskew images ...
> Defining HoG parameters ...
> Calculating HoG descriptor for every image ...
> Spliting data into training (90%) and test set (10%)...
> Training SVM model ...
> Saving SVM model ...
> Frame:0
> Traceback (most recent call last):
>   File "main.py", line 384, in <module>
>     main(args)
>   File "main.py", line 272, in main
>     coordinate, image, sign_type, text = localization(frame, args.min_size_components, args.similitary_contour_with_circle, model, count, current_sign)
>   File "main.py", line 171, in localization
>     sign, coordinate = findLargestSign(original_image, contours, similitary_contour_with_circle, 15)
>   File "main.py", line 122, in findLargestSign
>     M = cv2.moments(c)
> cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wwma2wne\opencv\modules\imgproc\src\moments.cpp:602: error: (-210:Unsupported format or combination of formats)  in function 'cv::moments'
> ```
> 
> Could you help me out with this problem?

how did you solve this error .I am getting the same error

**Comment by hoanglehaithanh** [comment]
@Anupreetadas  Use OpenCV3 or upgrade the code base to OpenCV4.  Sorry but this project is old and deprecated

**Comment by Flash715** [comment]
Thank you sir. Solved.

First delete your cv2 lib then 
conda install -c menpo opencv3
