### ISSUE TITLE
Include the default test video `MVI_1049.avi`

### ISSUE THREAD

**Issue by nirmalsnair** [ghostbbbmt/Traffic-Sign-Classification#4]
Kindly include the test video `MVI_1049.avi` so that an output similar to `demo.gif` can be obtained.

**Comment by hoanglehaithanh** [comment]
> Kindly include the test video `MVI_1049.avi` so that an output similar to `demo.gif` can be obtained.

Done. I also change the default param in `main.py` for new file location.

**Comment by nirmalsnair** [comment]
Thanks!
