### ISSUE TITLE
 error: (-210:Unsupported format or combination of formats)  in function 'cv::moments'

### ISSUE THREAD

**Issue by Firilacroco** [ghostbbbmt/Traffic-Sign-Classification#5]
Hi! I'm getting the following error when trying to run the code using your video:

` Frame:0
Traceback (most recent call last):
  File "main.py", line 384, in <module>
    main(args)
  File "main.py", line 272, in main
    coordinate, image, sign_type, text = localization(frame, args.min_size_components, args.similitary_contour_with_circle, model, count, current_sign)
  File "main.py", line 171, in localization
    sign, coordinate = findLargestSign(original_image, contours, similitary_contour_with_circle, 15)
  File "main.py", line 122, in findLargestSign
    M = cv2.moments(c)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\moments.cpp:696: error: (-210:Unsupported format or combination of formats)  in function 'cv::moments'`

Do you have any idea what's wrong?

Thanks!

**Comment by Firilacroco** [comment]
I found out the issue was I was using OpenCV4. Works now. Thanks!

**Comment by mayab12** [comment]
hello 
I m having the same problem 
what version of opencv should I use ?

**Comment by hoanglehaithanh** [comment]
@mayab12  you can use OpenCV3

**Comment by vstadnytskyi** [comment]
I am having the same problem. Is it a bug in moments function?

it works fine with int 16 numpy array and doesn't work with int 64. I wonder if there is an overflow problem.

**Comment by hoanglehaithanh** [comment]
@vstadnytskyi please refer this issue on Stackoverflow:
https://stackoverflow.com/questions/48453576/opencv-error-unsupported-format-or-combination-of-formats-unsupported-combinat

**Comment by nmcvanson** [comment]
@hoanglehaithanh chào a! em cũng gặp lỗi tương tự như phía bên trên. Có thể sửa lỗi này như thế nào ạ? em cảm ơn!
(Frame:0 Traceback (most recent call last): File "main.py", line 384, in <module> main(args) File "main.py", line 272, in main coordinate, image, sign_type, text = localization(frame, args.min_size_components, args.similitary_contour_with_circle, model, count, current_sign) File "main.py", line 171, in localization sign, coordinate = findLargestSign(original_image, contours, similitary_contour_with_circle, 15) File "main.py", line 122, in findLargestSign M = cv2.moments(c) cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\moments.cpp:696: error: (-210:Unsupported format or combination of formats) in function 'cv::moments')

**Comment by hoanglehaithanh** [comment]
@nmcvanson em cài OpenCV3 nhé

**Comment by StamT** [comment]
Plz give me detail about cv3 and how to install it by pyCharm

**Comment by StamT** [comment]
def constrastLimit(image):
    img_hist_equalized = cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
    **channel = cv2.split(img_hist_equalized)
    channels = list(channel)
    channels[0] = cv2.equalizeHist(channels[0])**
    img_hist_equalized = cv2.merge(channels)
    img_hist_equalized = cv2.cvtColor(img_hist_equalized, cv2.COLOR_YCrCb2BGR)
    return img_hist_equalized

additionally you can try to import opencv-python version 3.4.17.61 (it's working for me)

**Comment by PREMSAI2K1** [comment]
> @mayab12 you can use OpenCV3

pip install opencv-python
This command is enough to install opencv3 or there is another command

**Comment by PREMSAI2K1** [comment]
> I found out the issue was I was using OpenCV4. Works now. Thanks!



> I found out the issue was I was using OpenCV4. Works now. Thanks!

how to install opencv4

**Comment by PREMSAI2K1** [comment]
Traceback (most recent call last):
  File "c:\Users\user\Desktop\Traffic-Sign-Detection-master\main.py", line 386, in <module>
    main(args)
  File "c:\Users\user\Desktop\Traffic-Sign-Detection-master\main.py", line 274, in main
    coordinate, image, sign_type, text = localization(frame, args.min_size_components, args.similitary_contour_with_circle, model, count, current_sign)
  File "c:\Users\user\Desktop\Traffic-Sign-Detection-master\main.py", line 173, in localization
    sign, coordinate = findLargestSign(original_image, contours, similitary_contour_with_circle, 15)
  File "c:\Users\user\Desktop\Traffic-Sign-Detection-master\main.py", line 124, in findLargestSign
    M = cv2.moments(c)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\moments.cpp:602: error: (-210:Unsupported format or combination of formats)  in function 'cv::moments'

--->now how to run the code
