### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

### ISSUE THREAD

**Issue by ivanmonteiro** [ghostbbbmt/Traffic-Sign-Classification#6]
I'm having this problem executing the code: (Tested on windows and linux with opencv 3.4.4)

Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main(args)
  File "main.py", line 299, in main
    roi = cv2.cvtColor(roi, cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by hoanglehaithanh** [comment]
Check your image. Make sure your image is in correct format and loaded successfully
Ref: https://stackoverflow.com/questions/52676020/opencv-src-empty-in-function-cvtcolor-error

**Comment by Kashish121** [comment]
Hey @ivanmonteiro could you find out a possible solution? I am getting the same error.
> parser.add_argument(
      '--file_name',
      default= "./MVI_1049.avi",
      help= "Video to be analyzed"
      )
    
The video file is present in the desired location too.

**Comment by ivanmonteiro** [comment]
> Hey @ivanmonteiro could you find out a possible solution? I am getting the same error.
> 
> > parser.add_argument(
> > '--file_name',
> > default= "./MVI_1049.avi",
> > help= "Video to be analyzed"
> > )
> 
> The video file is present in the desired location too.

@Kashish121 Sorry, It's been so long since I had this error and honestly I don't remeber that exactly I did to solve this problem. What I remember is that I was using Windows and switched to Linux because I was having many issues on Windows at the time. I remember that transition reduced considerably the number of issues I was having with those computer vision algorithms. 

Whish you the best luck.
